let div = document.createElement('div');
let textNode = document.createTextNode('Анекдоты ');
document.body.append(div);
div.append(textNode);
let joke1 = document.createElement('joke1');
let j1 = document.createTextNode(' 1. Второй закон политической термодинамики: "Бомбы стремятся лететь туда, где нефть дешевле". anekdotov.net ');
document.body.append(joke1);
joke1.append(j1);
let p = document.createElement('p');
let j2 = document.createTextNode(' 2. Звонок в 4 утра: — Алло! А у вас стадо оленей не пробегало? Спокойный ответ: — Ты что отстал? anekdotov.net');
document.body.append(p);
p.append(j2);
let p1 = document.createElement('p1');
let j3 = document.createTextNode(' 3 .— Чем отличаются политики от программистов? — Программистам платят за те программы, которые реально работают. anekdotov.net .');
document.body.append(p1);
p1.append(j3);
div.classList.add('title');
let title = document.querySelector('.title');
title.style.textAlign = "center";